# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "tfstate"
    key                  = "live/dev/key_vault/terraform.tfstate"
    resource_group_name  = "terraform-state-rg"
    storage_account_name = "tfstateaccount"
  }
}
